# Generated by Django 6.0.5 on 2026-06-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Пусто = бессрочно.', null=True, verbose_name='Истекает'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Список: ["read", "publish", "delete", "status", "stats"].', verbose_name='Разрешения'),
        ),
    ]
