# Generated by Django 6.0.5 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_platform_hardening"),
        ("blog", "0011_platform_hardening"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishPackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.CharField(max_length=128)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("state", models.CharField(choices=[("pending", "В обработке"), ("done", "Завершён"), ("failed", "Ошибка")], db_index=True, default="pending", max_length=16)),
                ("storage_names", models.JSONField(blank=True, default=list)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("api_key", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="publish_packages", to="api.apikey")),
                ("post", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="publish_packages", to="blog.post")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="publishpackage",
            constraint=models.UniqueConstraint(fields=("api_key", "idempotency_key"), name="unique_publish_package_key"),
        ),
    ]
