# Generated by Django 6.0 on 2025-12-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content_html_alter_post_content'),
    ]

    operations = [
    ]
