# Generated by Django 6.0.5 on 2026-05-29 09:58

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_convert_existing_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=blog.models.post_media_upload_to, verbose_name='Файл')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_slug', models.CharField(blank=True, max_length=255, verbose_name='URL-имя файла')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Медиафайл поста',
                'verbose_name_plural': 'Медиафайлы постов',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'original_filename'), name='unique_media_filename_per_post'), models.UniqueConstraint(fields=('post', 'file_slug'), name='unique_media_slug_per_post')],
            },
        ),
    ]
