# Generated by Django 6.0.5 on 2026-05-29 14:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_is_published_to_status(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    Post.objects.filter(is_published=False).update(status="draft")
    Post.objects.filter(is_published=True).update(status="published")


def migrate_status_to_is_published(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    Post.objects.filter(status="draft").update(is_published=False)
    Post.objects.exclude(status="draft").update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_postmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="URL-slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="URL-slug")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                db_index=True,
                default="published",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.RunPython(migrate_is_published_to_status, migrate_status_to_is_published),
        migrations.RemoveField(
            model_name="post",
            name="is_published",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="blog.tag",
                verbose_name="Теги",
            ),
        ),
    ]
