# Generated by Django 6.0.5 on 2026-05-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categories_tags_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='SessionPostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Первый просмотр')),
                ('liked_at', models.DateTimeField(blank=True, null=True, verbose_name='Лайк поставлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_interactions', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Сессионное действие с постом',
                'verbose_name_plural': 'Сессионные действия с постами',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session_key', 'liked_at'], name='blog_sessio_session_0ec8b7_idx'), models.Index(fields=['post', 'viewed_at'], name='blog_sessio_post_id_2f2160_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'post'), name='unique_session_interaction_per_post')],
            },
        ),
    ]
