# Generated by Hermes Agent on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_like_count_post_view_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default="", verbose_name="Описание"),
            preserve_default=False,
        ),
    ]
