# Generated by Django 6.0.5 on 2026-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('article', 'Статья'), ('video', 'Видео'), ('audio', 'Аудио'), ('podcast', 'Подкаст')], db_index=True, default='article', max_length=20, verbose_name='Тип записи'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, verbose_name='URL основного медиа'),
        ),
        migrations.AddField(
            model_name='post',
            name='timecodes',
            field=models.JSONField(blank=True, default=list, help_text='Список объектов: time, seconds, label.', verbose_name='Таймкоды'),
        ),
    ]
