# Generated by Django 6.0.5 on 2026-06-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_content_types_timecodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail_card',
            field=models.FileField(blank=True, null=True, upload_to='posts/thumbnails/', verbose_name='Карточное превью (400×300)'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail_og',
            field=models.FileField(blank=True, null=True, upload_to='posts/thumbnails/', verbose_name='OG-превью (1200×630)'),
        ),
    ]
