# Generated by Django 6.0.5 on 2026-06-28 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_platform_hardening'),
        ('blog', '0010_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. Null = active.', null=True, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Заполняется при переходе в published. Для scheduled publishing.', null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, help_text='Идемпотентный ключ для агентских публикаций.', max_length=200, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], db_index=True, default='published', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('published', 'Опубликовано'), ('updated', 'Обновлено'), ('status_changed', 'Смена статуса'), ('deleted', 'Удалено'), ('restored', 'Восстановлено')], db_index=True, max_length=20, verbose_name='Действие')),
                ('post_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок поста (снапшот)')),
                ('post_slug', models.CharField(blank=True, max_length=200, verbose_name='Slug поста (снапшот)')),
                ('api_key_name', models.CharField(blank=True, max_length=100, verbose_name='Имя ключа (снапшот)')),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные: old_status, new_status, source_id и т.д.', verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='api.apikey', verbose_name='API ключ')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата просмотра')),
                ('read_depth', models.FloatField(default=0.0, help_text='Доля прочитанного контента: 0.0 — 1.0.', verbose_name='Глубина чтения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Просмотр поста',
                'verbose_name_plural': 'Просмотры постов',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', 'viewed_at'], name='blog_postvi_post_id_b8425b_idx'), models.Index(fields=['session_key', 'viewed_at'], name='blog_postvi_session_d3cc0a_idx')],
            },
        ),
    ]
