# Generated by Django 6.0.5 on 2026-09-02 19:24

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_platform_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(max_length=500, upload_to=blog.models.post_media_upload_to, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='thumbnail_card',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='posts/thumbnails/', verbose_name='Карточное превью (400×300)'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='thumbnail_og',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='posts/thumbnails/', verbose_name='OG-превью (1200×630)'),
        ),
    ]
